# This file was auto-generated by Fern from our API Definition.

import typing

from .typed_media_content import TypedMediaContent
from .typed_text import TypedText

ChatMessageChunkContentItem = typing.Union[TypedText, TypedMediaContent]
