# This file was auto-generated by Fern from our API Definition.

import typing

from .chat_round_chunk_content_item import ChatRoundChunkContentItem

Content = typing.Union[str, typing.List[ChatRoundChunkContentItem]]
