# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.chat_response import ChatResponse
from ...types.chunk_chat_response import ChunkChatResponse

ChatChatResponse = typing.Union[ChatResponse, ChunkChatResponse]
